on:
    workflow_dispatch:
    push:
       branches:
         - main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
    
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      #- name: Setup Python and Jupyter
      #  uses: actions/setup-python@v4
      #  with:
      #    python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
      #- run: pip install jupyter
      #- run: pip install -r requirements.txt
    
      - name: Install R
        uses: r-lib/actions/setup-r@v2
    
      - name: Session info
        run: Rscript -e 'sessionInfo()'
    
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2 # update
    
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libharfbuzz-dev \
            libfribidi-dev
        
      - name: Install tinytex
        uses: r-lib/actions/setup-tinytex@v2 # update
        
      - name: Install additional LaTeX packages
        run: |
          #tlmgr install url
          #tlmgr install underscore
          tlmgr update --self
          tlmgr install \
            collectbox \
            titling \
            framed \
            mdframed \
            ulem \
            hyperref \
            url \
            underscore \
            xcolor \
            csquotes
    
      - name: Install package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2 # update
    
      #- name: Install remote packages
      #  run: |
      #   Rscript -e "install.packages('rstan', repos = c('https://mc-stan.org/r-packages/', getOption('repos')))"
      #  # Rscript -e 'remotes::install_github("DevPsyLab/petersenlab")'

      - name: Render & Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages

      - name: List files in workspace
        if: always()
        run: |
          ls -lh
          find . -type f
          
      - name: Archive production artifacts
        if: always() # ensures it runs even if previous steps fail
        uses: actions/upload-artifact@v4 # update
        with:
          name: site
          path: _site/
